trigger:
- master
- staging

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'caa3826d-6635-4731-8176-80807744a160'
  
  # Web app name
  webAppName: 'sparked-server'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
      
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm lint
        npm run build
      displayName: 'npm install, build'
      
   
